
```{r}
link='https://github.com/auroraD-11/542Teamdata/raw/master/TEAMdata.RDS'
myFile=url(link)

fromPy=readRDS(file = myFile)

row.names(fromPy)=NULL
```

```{r}
str(fromPy[,c(1,2,3,4)][])
```
```{r}
dfClus=fromPy[,c(2,3)]
```
```{r}
row.names(dfClus)=fromPy$Country
head(dfClus)
```
```{r}
set.seed(999)
```

```{r}
library(cluster)
dfClus_D=cluster::daisy(x=dfClus,metric="gower")
```

```{r}
library(dbscan)
minNeighs=4
kNNdistplot(dfClus_D, k = minNeighs)
abline(h=.05, col = "red", lty=2)
```

```{r}
distance=0.05
res.db = dbscan::dbscan(dfClus_D, eps=distance, 
                     minPts=minNeighs)
```

```{r}
res.db
```

```{r}
fromPy$db=as.factor(res.db$cluster)
```

```{r}
library(ggplot2)

projectedData = cmdscale(dfClus_D, k=4)
fromPy$dim1 = projectedData[,2]
fromPy$dim2 = projectedData[,3]
```

```{r}
base= ggplot(data=fromPy,
             aes(x=dim1, y=dim2,
                 label=Country)) 
base + geom_text(size=2)
```

```{r}
dbPlot= base + labs(title = "DBSCAN") + geom_point(aes(color=db),
                                               show.legend = T) 
dbPlot
```
Annotating ouyliers:
```{r}
library(ggrepel)

dbPlot + geom_text_repel(size=3,aes(label=Country))

LABEL=ifelse(fromPy$db==0,fromPy$Country,"")

dbPlot + geom_text_repel(aes(label=LABEL))
```

```{r}
library(ggplot2)

projectedData = cmdscale(dfClus_D, k=4)
fromPy$dim1 = projectedData[,2]
fromPy$dim2 = projectedData[,4]
```


```{r}
base= ggplot(data=fromPy,
             aes(x=dim1, y=dim2,
                 label=Country)) 
base + geom_text(size=2)
```

```{r}
dbPlot= base + labs(title = "DBSCAN") + geom_point(aes(color=db),
                                               show.legend = T) 
dbPlot
```

```{r}
library(ggrepel)

dbPlot + geom_text_repel(size=3,aes(label=Country))

LABEL=ifelse(fromPy$db==0,fromPy$Country,"")

dbPlot + geom_text_repel(aes(label=LABEL))
```


```{r}
link='https://github.com/argolden/gini/raw/master/TEAMdata.RDS'
# a RDS file from the web needs:
myFile=url(link)

# reading in data:
fromPy=readRDS(file = myFile)

# reset indexes to R format:
row.names(fromPy)=NULL
```


```{r}
fromPy
```


```{r}
fromPy$PolicyPlan    <- factor(ifelse(fromPy$PolicyPlan == "Yes", 1, 0))
```


```{r}
fromPy
```

```{r}
hypo=formula(scoreofhappiness~ GINI + PolicyPlan)

colsNeeded=c('scoreofhappiness', 'GINI','PolicyPlan')

str(fromPy[,colsNeeded])

DataRegGauss=fromPy[,colsNeeded]

row.names(DataRegGauss)=fromPy$Country

gauss=glm(hypo,data = DataRegGauss,family = 'gaussian')

summary(gauss)
```


```{r}
gauss2=lm(hypo,data = DataRegGauss)

summary(gauss2)
```


```{r}
with(summary(gauss), 1 - deviance/null.deviance)
```


```{r}
anova(gauss,test="Chisq")

```

```{r}
library(rsq)
rsq(gauss,adj=T)

```

```{r}
plot(gauss,1)
```


```{r}
plot(gauss,2)
```


```{r}
shapiro.test(gauss$residuals)
```


```{r}
plot(gauss, 3)
```


```{r}
library(lmtest)
bptest(gauss)
```

```{r}
library(car)
vif(gauss)
```

```{r}
plot(gauss,5)
```


```{r}
library(sjPlot)

plot_models(gauss,vline.color = "grey")
```


